# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191111_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
            preserve_default=False,
        ),
    ]
